#!/bin/sh
if [ -z "${KUBERNETES_API_TOKEN}" ]; then
    if [ -s /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
        export KUBERNETES_API_TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token 2> /dev/null)"
    fi
fi

if [ -n "${INTERVAL}" ]; then
    while true; do
        diecast ${DIECAST_ARGS} ${@} > "${OUTPUT_FILE:-/dev/stdout}"
        sleep "${INTERVAL}"
    done
else
    exec diecast ${DIECAST_ARGS} ${@} > "${OUTPUT_FILE:-/dev/stdout}"
fi