#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

/usr/bin/ssh-keygen -A

cat <<EOF
sshd container
Network: $(/sbin/ip address show dev eth0)

EOF

if [ -s /init.rc ]; then
    echo "Running /init.rc script in background..." 1>&2
    bash /init.rc &
fi

/usr/sbin/sshd -D -e